[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://new-perfect-tution-classes.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"